AllCops:
  TargetRubyVersion: 2.0
  DisplayCopNames: true
  Exclude:
    - vendor/**/*
    - spec/dummy/rails-?/**/*

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods:
    - describe
