AllCops:
  TargetRubyVersion: 2.0
  DisplayCopNames: true
  Exclude:
    - spec/dummy/rails-?/**/*

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - lib/preserve.rb

Metrics/MethodLength:
  Exclude:
    - lib/preserve.rb

Metrics/BlockLength:
  ExcludedMethods:
    - describe
