AllCops:
  TargetRubyVersion: 2.0
  DisplayCopNames: true
  Exclude:
    - spec/dummy/**/*

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - lib/preserve.rb

Metrics/MethodLength:
  Exclude:
    - lib/preserve.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/LineLength:
  Exclude:
    - preserve.gemspec
