language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3

gemfile:
  - gemfiles/nokogiri_1.6.gemfile
  - gemfiles/nokogiri_1.8.gemfile

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/nokogiri_1.8.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/nokogiri_1.8.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/nokogiri_1.6.gemfile
    - rvm: 2.2.10
      gemfile: gemfiles/nokogiri_1.6.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/nokogiri_1.6.gemfile
    - rvm: 2.4.5
      gemfile: gemfiles/nokogiri_1.6.gemfile
    - rvm: 2.5.3
      gemfile: gemfiles/nokogiri_1.6.gemfile
