language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.5
  - 2.6.2

gemfile:
  - gemfiles/nokogiri_1.6.gemfile
  - gemfiles/nokogiri_1.8.gemfile
  - gemfiles/nokogiri_1.10.gemfile

matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/nokogiri_1.8.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/nokogiri_1.10.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/nokogiri_1.8.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/nokogiri_1.10.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/nokogiri_1.10.gemfile
    - rvm: 2.2.10
      gemfile: gemfiles/nokogiri_1.10.gemfile

before_install:
  - gem install bundler -v 1.17.3

install:
  - bundle _1.17.3_ install --jobs=3 --retry=3
