language: ruby

rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.1

gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_6.gemfile

matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/rails_5.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails_6.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_5.gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/rails_6.gemfile
    - rvm: 2.2.10
      gemfile: gemfiles/rails_6.gemfile
    - rvm: 2.3.8
      gemfile: gemfiles/rails_6.gemfile
    - rvm: 2.4.10
      gemfile: gemfiles/rails_6.gemfile
    - rvm: 2.7.1
      gemfile: gemfiles/rails_3.gemfile
    - rvm: 2.7.1
      gemfile: gemfiles/rails_4.gemfile

before_install:
  - gem install bundler -v 1.17.3

install:
  - bundle _1.17.3_ install --jobs=3 --retry=3

script:
  - bundle _1.17.3_ exec rspec
  - bundle _1.17.3_ exec rubocop
